### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dilawar** [ananthamurthy/eyeBlinkBehaviour#12]
- [x] Add support for treadmill motion. Two digital PINs.
- [x] If camera fails or not, arduino data must be saved. 
- [x] Reduce the length of command line options.
- [x] Imaging trigger PIN in arduino.
